[[redirects]]
  from = "/cury"
  to = "/cury.html"
  status = 200

[[redirects]]
  from = "/wavebio"
  to = "/wavebio.html"
  status = 200

[[redirects]]
  from = "/spark"
  to = "/spark.html"
  status = 200
